# ~~~~~~~~~~~~~~~~~~~~ SCROLLBACK ~~~~~~~~~~~~~~~~~~~~
scrollback_lines 25000

# ~~~~~~~~~~~~~~~~~~~~ THEME ~~~~~~~~~~~~~~~~~~~~
# Theme handled by auto-switching (dark-theme.auto.conf / light-theme.auto.conf)
# include themes/mocha.conf
# include themes/latte.conf
# Titlebar matches terminal background (works with auto-switching)
macos_titlebar_color background


# ~~~~~~~~~~~~~~~~~~~~ FONT ~~~~~~~~~~~~~~~~~~~~
font_family      family="JetBrainsMono Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 12.0
# text_composition_strategy legacy

# ~~~~~~~~~~~~~~~~~~~~ KEY BINDINGS ~~~~~~~~~~~~~~~~~~~~ 
# map ctrl+f find_mode
# map cmd+f launch --type=overlay --stdin-source=@screen_scrollback /opt/homebrew/bin/fzf --no-sort --no-mouse --exact -i
# map cmd+f launch --type=overlay --stdin-source=@screen_scrollback /bin/sh -c "/opt/homebrew/bin/fzf --no-sort --no-mouse --exact -i --tac | kitty +kitten clipboard"
# map cmd+f launch --type=overlay --stdin-source=@screen_scrollback /bin/sh -c 'fzf_selected=$(/opt/homebrew/bin/fzf --no-sort --no-mouse --exact -i --tac); if [ -n "$fzf_selected" ]; then echo "$fzf_selected" | kitty +kitten clipboard; fi'
map cmd+f combine : show_scrollback : send_text normal,application /
# Cmd+1: sends ^T1 (0x31)
map cmd+1 send_text all \x131

# Cmd+2: sends ^T2 (0x32)
map cmd+2 send_text all \x132

# Cmd+3: sends ^T3 (0x33)
map cmd+3 send_text all \x133

# Cmd+4: sends ^T4 (0x34)
map cmd+4 send_text all \x134

# Cmd+5: sends ^T5 (0x35)
map cmd+5 send_text all \x135

# Cmd+6: sends ^T6 (0x36)
map cmd+6 send_text all \x136

# Cmd+7: sends ^T7 (0x37)
map cmd+7 send_text all \x137

# Cmd+8: sends ^T8 (0x38)
map cmd+8 send_text all \x138

# Cmd+9: sends ^T9 (0x39)
map cmd+9 send_text all \x139


# Shift+Cmd+|: sends ^T | (vertical bar) -> split window vertically (into panes)
map cmd+shift+= send_text all \x13=
# map cmd+shift+| send_text all \x13-

# Shift+Cmd+_: sends ^T - (the hyphen character) -> split window horizontally (into panes)
map cmd+shift+- send_text all \x13-

# Shift+Cmd+C: sends ^T x plus a newline (0x78 then \n) -> close pane
map cmd+shift+c send_text all \x13x


# Shift+Cmd+N: sends ^T c (0x63) -> new window
map cmd+shift+n send_text all \x13c

# Shift+Cmd+W: sends ^T & (0x26) -> close window
map cmd+shift+w send_text all \x13&

# Cmd+N: sends ^T n (0x6E) -> next window
map cmd+n send_text all \x13n

# Cmd+P: sends ^T p (0x70) -> previous window
map cmd+p send_text all \x13p

# Cmd+L: sends ^T ; (the semicolon character) -> last window
map cmd+l send_text all \x13;


# Shift+Cmd+J: sends ^T j (0x6A) -> pane below
map shift+cmd+j send_text all \x13j

# Shift+Cmd+K: sends ^T k (0x6B) -> pane above
map shift+cmd+k send_text all \x13k

# Shift+Cmd+L: sends ^T l (0x6C) -> right pane
map shift+cmd+l send_text all \x13l

# Shift+Cmd+H: sends ^T h (0x68) -> left pane
map shift+cmd+h send_text all \x13h


