use crate::appearance::Appearance;
use crate::config::{expand_tilde, PathsConfig};
use crate::theme::{
    get_palette, CatppuccinFlavor, Contrast, Palette, ThemeFamily,
};
use crate::cmd::run_with_timeout;
use std::fs;
use std::process::Command;
use std::time::Duration;

const KITTY_TIMEOUT: Duration = Duration::from_secs(2);

/// kitty >= 0.38 picks between three auto.conf files using the OS-reported
/// TRI-state, not a boolean.
///
/// This matters on GNOME/Ubuntu, where switching to light mode reports
/// *no-preference* rather than prefer-light. Writing only dark and light there
/// means kitty matches neither file and silently falls back to whatever
/// kitty.conf says — the user toggles to light and kitty keeps stale colours,
/// with no error anywhere. Writing the extra file is harmless on macOS, which
/// only ever reports dark or light.
const LIGHT_AUTO_CONFS: &[&str] = &["light-theme.auto.conf", "no-preference-theme.auto.conf"];

/// Generate a complete kitty color conf from a palette.
fn generate_conf(palette: &Palette) -> String {
    let t = &palette.terminal;
    format!(
        "\
# Auto-generated by theme-manager — do not edit manually

foreground              {fg}
background              {bg}
selection_foreground    {bg}
selection_background    {fg}

cursor                  {fg}
cursor_text_color       {bg}

url_color               {blue}

active_border_color     {blue}
inactive_border_color   {bg2}
bell_border_color       {yellow}

wayland_titlebar_color  system
macos_titlebar_color    {bg}

active_tab_foreground   {bg}
active_tab_background   {blue}
inactive_tab_foreground {fg_dim}
inactive_tab_background {bg1}
tab_bar_background      {bg_dim}

mark1_foreground {bg}
mark1_background {blue}
mark2_foreground {bg}
mark2_background {purple}
mark3_foreground {bg}
mark3_background {aqua}

color0  {c0}
color8  {c8}
color1  {c1}
color9  {c9}
color2  {c2}
color10 {c10}
color3  {c3}
color11 {c11}
color4  {c4}
color12 {c12}
color5  {c5}
color13 {c13}
color6  {c6}
color14 {c14}
color7  {c7}
color15 {c15}
",
        fg = palette.fg,
        bg = palette.bg,
        blue = palette.blue,
        bg2 = palette.bg2,
        yellow = palette.yellow,
        bg1 = palette.bg1,
        bg_dim = palette.bg_dim,
        fg_dim = palette.fg_dim,
        purple = palette.purple,
        aqua = palette.aqua,
        c0 = t[0],
        c1 = t[1],
        c2 = t[2],
        c3 = t[3],
        c4 = t[4],
        c5 = t[5],
        c6 = t[6],
        c7 = t[7],
        c8 = t[8],
        c9 = t[9],
        c10 = t[10],
        c11 = t[11],
        c12 = t[12],
        c13 = t[13],
        c14 = t[14],
        c15 = t[15],
    )
}

/// Write both dark-theme.auto.conf and light-theme.auto.conf for the given theme.
/// Called when the user changes theme family or variant (not on every appearance switch).
///
/// Invariant: after this function succeeds, both auto.conf files exist and are
/// consistent with the requested family + variant.
pub fn write_auto_confs(
    family: ThemeFamily,
    variant: &str,
    paths: &PathsConfig,
) -> Result<(), String> {
    let kitty_dir = expand_tilde(&paths.kitty_config);

    if !kitty_dir.exists() {
        return Err(format!("kitty config dir not found: {}", kitty_dir.display()));
    }

    match family {
        ThemeFamily::Catppuccin => {
            let themes_dir = kitty_dir.join("themes");
            let dark_flavor = CatppuccinFlavor::parse(variant);
            let dark_src = themes_dir.join(dark_flavor.kitty_file());
            let light_src = themes_dir.join(CatppuccinFlavor::Latte.kitty_file());

            copy_theme_file(&dark_src, &kitty_dir.join("dark-theme.auto.conf"))?;
            for name in LIGHT_AUTO_CONFS {
                copy_theme_file(&light_src, &kitty_dir.join(name))?;
            }
        }
        _ => {
            let contrast = Contrast::parse(variant);
            let dark_palette = get_palette(family, contrast, Appearance::Dark);
            let light_palette = get_palette(family, contrast, Appearance::Light);

            fs::write(
                kitty_dir.join("dark-theme.auto.conf"),
                generate_conf(&dark_palette),
            )
            .map_err(|e| format!("write dark-theme.auto.conf: {}", e))?;

            let light_conf = generate_conf(&light_palette);
            for name in LIGHT_AUTO_CONFS {
                fs::write(kitty_dir.join(name), &light_conf)
                    .map_err(|e| format!("write {}: {}", name, e))?;
            }
        }
    }

    Ok(())
}

/// Copy a theme source file to the destination, with a clear error if the
/// source doesn't exist.
fn copy_theme_file(src: &std::path::Path, dst: &std::path::Path) -> Result<(), String> {
    if !src.exists() {
        return Err(format!("theme file not found: {}", src.display()));
    }
    fs::copy(src, dst).map_err(|e| {
        format!(
            "copy {} -> {}: {}",
            src.display(),
            dst.display(),
            e
        )
    })?;
    Ok(())
}

/// Signal kitty to reload its config. Kitty auto-selects the right
/// *.auto.conf based on current system appearance, so this is only strictly
/// needed when the *palette* changed rather than the appearance — but it is
/// cheap and makes a `theme-manager set` take effect immediately.
///
/// `-x` matters: without it `pkill` does an unanchored substring match on the
/// process name, and SIGUSR1's default disposition is to terminate. Any
/// unrelated process whose name merely contains "kitty" would be killed.
pub fn reload() -> Result<(), String> {
    let mut cmd = Command::new("pkill");
    cmd.args(["-x", "-USR1", "kitty"]);
    let _ = run_with_timeout(cmd, KITTY_TIMEOUT);
    Ok(())
}
