# vim:ft=kitty

## name:     Gruvbox Material Light Soft
## author:   sainnhe
## upstream: https://github.com/sainnhe/gruvbox-material

# The basic colors
foreground              #654735
background              #f2e5bc
selection_foreground    #f2e5bc
selection_background    #654735

# Cursor colors
cursor                  #654735
cursor_text_color       #f2e5bc

# URL underline color when hovering with mouse
url_color               #45707a

# Kitty window border colors
active_border_color     #45707a
inactive_border_color   #c9b99a
bell_border_color       #b47109

# OS Window titlebar colors
wayland_titlebar_color  system
macos_titlebar_color    #f2e5bc

# Tab bar colors
active_tab_foreground   #f2e5bc
active_tab_background   #45707a
inactive_tab_foreground #a89984
inactive_tab_background #d5c4a1
tab_bar_background      #d5c4a1

# Colors for marks
mark1_foreground #f2e5bc
mark1_background #45707a
mark2_foreground #f2e5bc
mark2_background #945e80
mark3_foreground #f2e5bc
mark3_background #4c7a5d

# The 16 terminal colors

# black
color0  #fbf1c7
color8  #928374

# red
color1  #c14a4a
color9  #c14a4a

# green
color2  #6c782e
color10 #6c782e

# yellow
color3  #b47109
color11 #b47109

# blue
color4  #45707a
color12 #45707a

# magenta
color5  #945e80
color13 #945e80

# cyan
color6  #4c7a5d
color14 #4c7a5d

# white
color7  #654735
color15 #654735
