# vim:ft=kitty

## name:     Gruvbox Light Soft
## author:   morhetz (Pavel Pertsev)
## upstream: https://github.com/morhetz/gruvbox

# The basic colors
foreground              #3c3836
background              #f2e5bc
selection_foreground    #f2e5bc
selection_background    #3c3836

# Cursor colors
cursor                  #3c3836
cursor_text_color       #f2e5bc

# URL underline color when hovering with mouse
url_color               #076678

# Kitty window border colors
active_border_color     #076678
inactive_border_color   #bdae93
bell_border_color       #b57614

# OS Window titlebar colors
wayland_titlebar_color  system
macos_titlebar_color    #f2e5bc

# Tab bar colors
active_tab_foreground   #f2e5bc
active_tab_background   #076678
inactive_tab_foreground #7c6f64
inactive_tab_background #d5c4a1
tab_bar_background      #d5c4a1

# Colors for marks
mark1_foreground #f2e5bc
mark1_background #076678
mark2_foreground #f2e5bc
mark2_background #8f3f71
mark3_foreground #f2e5bc
mark3_background #458588

# The 16 terminal colors

# black
color0  #fbf1c7
color8  #928374

# red
color1  #cc241d
color9  #9d0006

# green
color2  #98971a
color10 #79740e

# yellow
color3  #d79921
color11 #b57614

# blue
color4  #458588
color12 #076678

# magenta
color5  #b16286
color13 #8f3f71

# cyan
color6  #689d6a
color14 #427b58

# white
color7  #7c6f64
color15 #3c3836
