# Gruvbox Material Light theme for tmux
set -g status-style "bg=#f4e8be,fg=#654735"
set -g window-status-current-style "bg=#45707a,fg=#fbf1c7,bold"
set -g window-status-style "bg=#f4e8be,fg=#a89984"
set -g pane-border-style "fg=#e5d5ad"
set -g pane-active-border-style "fg=#45707a"
set -g message-style "bg=#f4e8be,fg=#654735"
set -g status-left ""
set -g status-right "#[fg=#fbf1c7,bg=#4c7a5d] session: #S "
